[2025-04-10T22:42:52.576+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio scheduled__2023-01-07T11:00:00+00:00 [queued]>
[2025-04-10T22:42:52.693+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio scheduled__2023-01-07T11:00:00+00:00 [queued]>
[2025-04-10T22:42:52.709+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-10T22:42:54.040+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_minio> on 2023-01-07 11:00:00+00:00
[2025-04-10T22:42:54.151+0000] {standard_task_runner.py:57} INFO - Started process 1084 to run task
[2025-04-10T22:42:54.194+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_and_verify_data', 'check_minio', 'scheduled__2023-01-07T11:00:00+00:00', '--job-id', '1439', '--raw', '--subdir', 'DAGS_FOLDER/dags_1.py', '--cfg-path', '/tmp/tmpfxtwni6u']
[2025-04-10T22:42:54.212+0000] {standard_task_runner.py:85} INFO - Job 1439: Subtask check_minio
[2025-04-10T22:42:54.487+0000] {task_command.py:415} INFO - Running <TaskInstance: generate_and_verify_data.check_minio scheduled__2023-01-07T11:00:00+00:00 [running]> on host 0821f6066d6a
[2025-04-10T22:42:52.375+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_and_verify_data' AIRFLOW_CTX_TASK_ID='check_minio' AIRFLOW_CTX_EXECUTION_DATE='2023-01-07T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-07T11:00:00+00:00'
[2025-04-10T22:42:52.382+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-10T22:42:52.390+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo "Checking MinIO bucket and file..."\n            docker exec minio mc alias set myminio http://127.0.0.1:9000 minioadmin minioadmin &&             docker exec minio mc ls myminio/ecommerce-data | grep orders.csv || exit 1\n            echo "MinIO check completed successfully."\n        ']
[2025-04-10T22:42:52.422+0000] {subprocess.py:86} INFO - Output:
[2025-04-10T22:42:52.429+0000] {subprocess.py:93} INFO - Checking MinIO bucket and file...
[2025-04-10T22:42:53.622+0000] {subprocess.py:93} INFO - Added `myminio` successfully.
[2025-04-10T22:42:55.064+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-10T22:42:55.152+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T22:42:55.196+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=generate_and_verify_data, task_id=check_minio, execution_date=20230107T110000, start_date=20250410T224252, end_date=20250410T224255
[2025-04-10T22:42:55.277+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1439 for task check_minio (Bash command failed. The command returned a non-zero exit code 1.; 1084)
[2025-04-10T22:42:55.335+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-10T22:42:55.414+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
