[2025-04-11T08:15:03.332+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-10T05:00:00+00:00 [queued]>
[2025-04-11T08:15:03.358+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-10T05:00:00+00:00 [queued]>
[2025-04-11T08:15:03.361+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-04-11T08:15:03.408+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_minio_task> on 2023-01-10 05:00:00+00:00
[2025-04-11T08:15:03.419+0000] {standard_task_runner.py:57} INFO - Started process 5803 to run task
[2025-04-11T08:15:03.430+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_and_verify_data', 'check_minio_task', 'scheduled__2023-01-10T05:00:00+00:00', '--job-id', '1665', '--raw', '--subdir', 'DAGS_FOLDER/dags_1.py', '--cfg-path', '/tmp/tmpoymobjz6']
[2025-04-11T08:15:03.440+0000] {standard_task_runner.py:85} INFO - Job 1665: Subtask check_minio_task
[2025-04-11T08:15:03.595+0000] {task_command.py:415} INFO - Running <TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-10T05:00:00+00:00 [running]> on host 0821f6066d6a
[2025-04-11T08:15:03.852+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_and_verify_data' AIRFLOW_CTX_TASK_ID='check_minio_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-10T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-10T05:00:00+00:00'
[2025-04-11T08:15:03.857+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T08:15:03.859+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo "Checking MinIO bucket and file..."\n            docker exec minio mc alias set myminio http://127.0.0.1:9000 minioadmin minioadmin &&             docker exec minio mc ls myminio/ecommerce-data | grep orders.csv || exit 1\n            echo "MinIO check completed successfully."\n        ']
[2025-04-11T08:15:03.894+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T08:15:03.898+0000] {subprocess.py:93} INFO - Checking MinIO bucket and file...
[2025-04-11T08:15:04.053+0000] {subprocess.py:93} INFO - Added `myminio` successfully.
[2025-04-11T08:15:04.264+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-11T08:15:04.288+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-11T08:15:04.296+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=generate_and_verify_data, task_id=check_minio_task, execution_date=20230110T050000, start_date=20250411T081503, end_date=20250411T081504
[2025-04-11T08:15:04.320+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1665 for task check_minio_task (Bash command failed. The command returned a non-zero exit code 1.; 5803)
[2025-04-11T08:15:04.369+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-11T08:15:04.398+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
