[2025-04-10T22:49:02.286+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-08T06:00:00+00:00 [queued]>
[2025-04-10T22:49:02.345+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-08T06:00:00+00:00 [queued]>
[2025-04-10T22:49:02.352+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-10T22:49:02.405+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_minio_task> on 2023-01-08 06:00:00+00:00
[2025-04-10T22:49:02.423+0000] {standard_task_runner.py:57} INFO - Started process 2460 to run task
[2025-04-10T22:49:02.493+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_and_verify_data', 'check_minio_task', 'scheduled__2023-01-08T06:00:00+00:00', '--job-id', '1506', '--raw', '--subdir', 'DAGS_FOLDER/dags_1.py', '--cfg-path', '/tmp/tmpykz3pr30']
[2025-04-10T22:49:02.512+0000] {standard_task_runner.py:85} INFO - Job 1506: Subtask check_minio_task
[2025-04-10T22:49:02.866+0000] {task_command.py:415} INFO - Running <TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-08T06:00:00+00:00 [running]> on host 0821f6066d6a
[2025-04-10T22:49:04.080+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_and_verify_data' AIRFLOW_CTX_TASK_ID='check_minio_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T06:00:00+00:00'
[2025-04-10T22:49:04.098+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-10T22:49:04.121+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo "Checking MinIO bucket and file..."\n            docker exec minio mc alias set myminio http://127.0.0.1:9000 minioadmin minioadmin &&             docker exec minio mc ls myminio/ecommerce-data | grep orders.csv || exit 1\n            echo "MinIO check completed successfully."\n        ']
[2025-04-10T22:49:04.204+0000] {subprocess.py:86} INFO - Output:
[2025-04-10T22:49:04.209+0000] {subprocess.py:93} INFO - Checking MinIO bucket and file...
[2025-04-10T22:49:04.677+0000] {subprocess.py:93} INFO - Added `myminio` successfully.
[2025-04-10T22:49:05.222+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-10T22:49:05.258+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T22:49:05.278+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=generate_and_verify_data, task_id=check_minio_task, execution_date=20230108T060000, start_date=20250410T224902, end_date=20250410T224905
[2025-04-10T22:49:05.645+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1506 for task check_minio_task (Bash command failed. The command returned a non-zero exit code 1.; 2460)
[2025-04-10T22:49:05.726+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-10T22:49:05.874+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
