[2025-04-11T08:09:51.620+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-10T01:00:00+00:00 [queued]>
[2025-04-11T08:09:51.784+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-10T01:00:00+00:00 [queued]>
[2025-04-11T08:09:51.800+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-11T08:09:53.201+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_minio_task> on 2023-01-10 01:00:00+00:00
[2025-04-11T08:09:53.225+0000] {standard_task_runner.py:57} INFO - Started process 5336 to run task
[2025-04-11T08:09:53.326+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_and_verify_data', 'check_minio_task', 'scheduled__2023-01-10T01:00:00+00:00', '--job-id', '1645', '--raw', '--subdir', 'DAGS_FOLDER/dags_1.py', '--cfg-path', '/tmp/tmp2mo1peli']
[2025-04-11T08:09:53.396+0000] {standard_task_runner.py:85} INFO - Job 1645: Subtask check_minio_task
[2025-04-11T08:09:54.092+0000] {task_command.py:415} INFO - Running <TaskInstance: generate_and_verify_data.check_minio_task scheduled__2023-01-10T01:00:00+00:00 [running]> on host 0821f6066d6a
[2025-04-11T08:09:54.766+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_and_verify_data' AIRFLOW_CTX_TASK_ID='check_minio_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-10T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-10T01:00:00+00:00'
[2025-04-11T08:09:54.800+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T08:09:54.814+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo "Checking MinIO bucket and file..."\n            docker exec minio mc alias set myminio http://127.0.0.1:9000 minioadmin minioadmin &&             docker exec minio mc ls myminio/ecommerce-data | grep orders.csv || exit 1\n            echo "MinIO check completed successfully."\n        ']
[2025-04-11T08:09:54.993+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T08:09:55.027+0000] {subprocess.py:93} INFO - Checking MinIO bucket and file...
[2025-04-11T08:09:56.089+0000] {subprocess.py:93} INFO - Added `myminio` successfully.
[2025-04-11T08:09:57.516+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-11T08:09:57.618+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-11T08:09:57.672+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=generate_and_verify_data, task_id=check_minio_task, execution_date=20230110T010000, start_date=20250411T080951, end_date=20250411T080957
[2025-04-11T08:09:58.903+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1645 for task check_minio_task (Bash command failed. The command returned a non-zero exit code 1.; 5336)
[2025-04-11T08:09:59.046+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-11T08:09:59.317+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
